package com.academicdashboard.backend.professor;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import com.academicdashboard.backend.calendar.Calendar;
import com.academicdashboard.backend.checklist.Checklist;
import com.academicdashboard.backend.course.Course;
import com.academicdashboard.backend.reminder.ReminderList;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "professor")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Professor {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Professor's Personal Info
    private String firstName;
    private String lastName;
    private String birthMonth; 
    private int birthDay;
    private int birthYear;

    //Professor's School Info
    private String schoolName;
    private String department;
    private String academicRole; //View Google Doc for all options
    private int apptYear;
    private String officeBuilding;
    private String officeRoom;
    private String researchArea;
    private List<OfficeHrs> officeHrs;

    //Professor's Account Info
    private String email;
    private String password;
    private String phone;

    //Data Relationships
    @DocumentReference
    private List<Course> courses;

    @DocumentReference
    private List<Calendar> calendars;

    @DocumentReference
    private List<Checklist> checklists;

    @DocumentReference
    private List<ReminderList> reminderList;

}
