package com.academicdashboard.backend.professor;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "professor")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Professor {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Professor's Personal Info
    private String firstName;
    private String lastName;
    private String birthMonth; 
    private int birthDay;
    private int birthYear;

    //Professor's School Info
    private String schoolName;
    private String department;
    private String academicRole; //View Google Doc for all options
    private int apptYear;
    private String officeBuilding;
    private String officeRoom;
    private String researchArea;
    private List<OfficeHrs> officeHrs;

    //Professor's Account Info
    private String email;
    private String password;
    private int phone;

    //Data Relationships
    private List<ObjectId> classes;
    private List<ObjectId> calendar;
    private List<ObjectId> checkLists;
    private List<ObjectId> reminders;
}
