package com.academicdashboard.backend.checklist;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "checkpoint")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Checkpoint {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    //Checkpoint's Detail
    private String list; //List it Belongs to (Might Delete)
    private String content; 
    private boolean isComplete;

    //Constructor: Called each time user creates a new checkpoint
    public Checkpoint(String content, boolean isComplete) {
        this.content = content;
        this.isComplete = isComplete;
    }
}
