package com.academicdashboard.backend.checklist;

import java.util.ArrayList;
import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Document(collection = "checklist")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Checklist {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    //CheckList's Details
    private String listId; //Used for Queries (JNanoId)
    private String title;

    @DocumentReference
    private List<Checkpoint> checkpoints;

    //Constructor: Individual Checklist is Created
    public Checklist(
            String listId,
            String title
        ) {

        this.listId = listId;
        this.title = title;
        this.checkpoints = new ArrayList<>();
    }

}
