package com.academicdashboard.backend.checklist;

import java.util.ArrayList;
import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "grouplist")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Grouplist {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Grouplist's Details
    private String groupId;
    private String title;

    @DocumentReference
    private List<Checklist> checklists;

    public Grouplist(
            String groupId,
            String title) {

        this.groupId = groupId;
        this.title = title;
        this.checklists = new ArrayList<>();
    }
}
