package com.academicdashboard.backend.reminder;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "reminder")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Reminder {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    //Reminders List's Details
    private String title;
    private String description;

    //Individual Reminders under this List
    private List<ObjectId> reminders; //Individual Reminders
}
