package com.academicdashboard.backend.student;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "student")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Student {

    @Id
    private ObjectId id; //MongoDB ObjectId

    //Student's Personal Info
    private String firstName;
    private String lastName;
    private String birthMonth; 
    private int birthDay;
    private int birthYear;

    //Student's School Info
    private String schoolName;
    private String gradeLevel; 
    private String major;
    private String minor;
    private String concentration;

    //Student's Account Info
    private String email;
    private String password;
    private int phone;

    //Data Relationships
    private List<ObjectId> classes;
    private List<ObjectId> calendar;
    private List<ObjectId> checkLists;
    private List<ObjectId> reminders;

    //Contructor without ObjectId
    public Student(
            String firstName,
            String lastName,
            String birthMonth,
            int birthDay,
            int birthYear,
            String schoolName,
            String gradeLevel,
            String major,
            String minor,
            String concentration,
            String email,
            String password,
            int phone
        ) {

        this.firstName = firstName;
        this.lastName = lastName;
        this.birthMonth = birthMonth;
        this.birthDay = birthDay;
        this.birthYear = birthYear;
        this.schoolName = schoolName;
        this.gradeLevel = gradeLevel;
        this.major = major;
        this.minor = minor;
        this.concentration = concentration;
        this.email = email;
        this.password = password;
        this.phone = phone;
    }
}
