package com.academicdashboard.backend.course;

import java.util.List;

import org.bson.types.ObjectId; //MongoDB ObjectId (AutoGenerated)
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.mapping.DocumentReference;

import com.academicdashboard.backend.student.Student;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Document(collection = "course")
@Getter
@Setter
@EqualsAndHashCode
@NoArgsConstructor
@AllArgsConstructor
public class Course {

    @Id
    private ObjectId id; //MongoDB ObjectId
    
    //Course Details
    private String crsDept; //Course Department
    private String crsTitle; //Course Title
    private String crsNum; //Course Number
    private String crsSection; //Course Section

    //Professor Information
    private String instructor;
    private ObjectId instructorId;

    //Date, Time, & Lecture
    private String firstDate;
    private String lastDate;
    private String semester;
    private int schoolYr;
    private List<LectureHrs> lecture;

    //Data Relationships
    @DocumentReference
    private List<Student> students;

    @DocumentReference
    private List<Syllabus> syllabusSection;

    @DocumentReference
    private List<Assignment> assignment;

    @DocumentReference
    private List<Test> test;

    @DocumentReference
    private List<Announcement> announcement;
}
